# Generated by Django 5.2.17 on 2026-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, unique=True)),
                ("ville", models.CharField(max_length=80)),
                ("secteur", models.CharField(max_length=80)),
                ("contact", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "entreprise",
                "verbose_name_plural": "entreprises",
                "ordering": ["nom"],
            },
        ),
    ]
