# Generated by Django 5.2.17 on 2026-09-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="libellé"
                    ),
                ),
            ],
            options={
                "verbose_name": "compétence",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="EnseignantReferent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenom", models.CharField(max_length=80, verbose_name="prénom")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "verbose_name": "enseignant référent",
                "verbose_name_plural": "enseignants référents",
                "ordering": ["nom", "prenom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenom", models.CharField(max_length=80, verbose_name="prénom")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("matricule", models.CharField(max_length=20, unique=True)),
                (
                    "promotion",
                    models.PositiveSmallIntegerField(
                        help_text="Année de sortie, par exemple 2027."
                    ),
                ),
                (
                    "competences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="etudiants",
                        to="stages.competence",
                        verbose_name="compétences",
                    ),
                ),
            ],
            options={
                "verbose_name": "étudiant",
                "ordering": ["nom", "prenom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("date_debut", models.DateField(verbose_name="début du stage")),
                ("date_fin", models.DateField(verbose_name="fin du stage")),
                (
                    "nb_places",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="nombre de places"
                    ),
                ),
                (
                    "competences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offres",
                        to="stages.competence",
                        verbose_name="compétences demandées",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offres",
                        to="stages.entreprise",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_debut", "titre"],
            },
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_depot",
                    models.DateField(auto_now_add=True, verbose_name="date de dépôt"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("deposee", "Déposée"),
                            ("retenue", "Retenue"),
                            ("refusee", "Refusée"),
                        ],
                        default="deposee",
                        max_length=10,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="stages.etudiant",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="stages.offre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_depot"],
            },
        ),
        migrations.CreateModel(
            name="TuteurEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenom", models.CharField(max_length=80, verbose_name="prénom")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuteurs",
                        to="stages.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "tuteur en entreprise",
                "verbose_name_plural": "tuteurs en entreprise",
                "ordering": ["nom", "prenom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=200)),
                (
                    "candidature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage",
                        to="stages.candidature",
                    ),
                ),
                (
                    "enseignant_referent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="stages.enseignantreferent",
                    ),
                ),
                (
                    "tuteur_entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="stages.tuteurentreprise",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="candidature",
            constraint=models.UniqueConstraint(
                fields=("etudiant", "offre"), name="une_candidature_par_offre"
            ),
        ),
    ]
